// Package admin Code generated by swaggo/swag. DO NOT EDIT
package admin

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/login": {
            "post": {
                "description": "后台管理系统登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录退出"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_auth.ReqAdminAuth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_auth.RespAdminAuth"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/account/logout": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "退出后台管理系统\n前端调用该接口，无需关注结果，自行清理掉请求头的 Authorization，页面跳转至首页\n后端可以执行清理redis缓存, 设置token黑名单等操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录退出"
                ],
                "summary": "退出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/account/user/create": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "创建新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_accountuser.ReqCreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_accountuser.RespUserDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/account/user/delete": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "删除单个用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/account/user/detail": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "获取用户详情",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "通过用户UUID获取用户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户UUID",
                        "name": "uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin_accountuser.RespUserDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/account/user/list": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "获取用户列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "数据创建结束区间",
                        "name": "create_time_end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "数据创建开始区间",
                        "name": "create_time_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "abc@abc.com",
                        "description": "邮箱,模糊查询",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "是否admin, 1 or 0",
                        "name": "is_admin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最近登录结束时间",
                        "name": "last_login_time_end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最近登录开始时间",
                        "name": "last_login_time_start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "Tom",
                        "description": "昵称,模糊查询",
                        "name": "nickname",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "13800138000",
                        "description": "手机号,模糊查询",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "INACTIVE",
                                "ACTIVE",
                                "FREEZE",
                                "DELETE"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "FREEZE",
                            "ACTIVE"
                        ],
                        "description": "用户状态",
                        "name": "status[]",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "826d6b1aa64d471d822d667e92218158",
                        "description": "用户UUID,精确匹配",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/goal-app_pkg_render.RespPageJson"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/admin_accountuser.RespUserDetail"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/account/user/update": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "更新用户数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_accountuser.ReqUpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/account/user/{uuid}/profile": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "用户个人资料",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户个人资料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/account/users/{uuid}/profile/update": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "更新用户个人资料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/system/config/create": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "创建系统配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置项"
                ],
                "summary": "创建系统配置项",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_systemconfig.ReqSystemConfigCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_systemconfig.RespSystemConfigItem"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/config/delete": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "删除系统配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置项"
                ],
                "summary": "删除系统配置项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/system/config/detail": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "系统配置项详情",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置项"
                ],
                "summary": "系统配置项详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "流水ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin_systemconfig.RespSystemConfigItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/system/config/list": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "系统配置项列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置项"
                ],
                "summary": "系统配置项列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "数据创建结束区间",
                        "name": "create_time_end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "数据创建开始区间",
                        "name": "create_time_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "配置说明",
                        "name": "desc",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "是否启用,0-否,1-是",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "配置名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "作用域,global-全局,admin-管理后台,app-前台应用",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "配置值",
                        "name": "value",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/goal-app_pkg_render.RespPageJson"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/admin_systemconfig.RespSystemConfigItem"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/config/update": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "更新系统配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置项"
                ],
                "summary": "更新系统配置项",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_systemconfig.ReqSystemConfigUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_systemconfig.RespSystemConfigItem"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/create": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "向 gen_tables 表中导入数据表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "向 gen_tables 表中导入数据表信息",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/admin_generator.ReqGenTableCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/delete": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "删除代码生成配置表数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "删除代码生成配置表数据",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/admin_generator.ReqDelTable"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/gencode": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "生成代码文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "生成代码文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "生成的表, 用\",\"分隔",
                        "name": "tables",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/list": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "获取已导入的数据表列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "获取已导入的数据表列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "数据创建结束区间",
                        "name": "create_time_end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "数据创建开始区间",
                        "name": "create_time_start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "表名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "表描述",
                        "name": "table_comment",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/goal-app_pkg_render.RespPageJson"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/admin_generator.RespGenTableItem"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/preview": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "预览代码生成内容",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "预览代码生成内容",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主键",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/admin_generator.RespPreviewItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/tables": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "获取数据库表名称列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "获取数据库表名称列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "数据创建结束区间",
                        "name": "create_time_end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "数据创建开始区间",
                        "name": "create_time_start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "表描述",
                        "name": "table_comment",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "表名称",
                        "name": "table_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/goal-app_pkg_render.RespPageJson"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/admin_generator.RespDbTable"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/tables/{id}/columns": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "获取数据库表每个列的信息",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "获取数据库表每个列的信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "表格ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/admin_generator.RespGenColumn"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/tables/{id}/columns/delete": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "删除代码生成配置表的行属性数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "删除代码生成配置表的行属性数据",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/admin_generator.ReqDelGenTableColumn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/tables/{id}/columns/update": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "更新生成代码表列信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "更新生成代码表列信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "表格ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/generator/update": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "更新代码生成配置表数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理--代码生成器"
                ],
                "summary": "更新代码生成配置表数据",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/admin_generator.ReqPreview"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/menus/create": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "创建菜单管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "创建菜单管理",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_systemmenu.ReqSystemMenuCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_systemmenu.RespSystemMenuItem"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/menus/delete": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "删除菜单管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "删除菜单管理",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/system/menus/detail": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "菜单管理详情",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "菜单管理详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "流水ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin_systemmenu.RespSystemMenuItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    }
                }
            }
        },
        "/system/menus/list": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "菜单管理列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "菜单管理列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "'权限标识'",
                        "name": "auth_tag",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "'前端组件'",
                        "name": "component",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "数据创建结束区间",
                        "name": "create_time_end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "数据创建开始区间",
                        "name": "create_time_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "'菜单图标'",
                        "name": "icon",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "'权限类型: dir=目录，menu=菜单，button=按钮''",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "'菜单名称'",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "'路由参数'",
                        "name": "params",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "'上级菜单ID'",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "'路由地址'",
                        "name": "route",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "'菜单排序'",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "'状态: disable=停用, enable=启用'",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/goal-app_pkg_render.RespPageJson"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "result": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/admin_systemmenu.RespSystemMenuItem"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/menus/tree": {
            "get": {
                "description": "菜单管理树结构数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "菜单管理树结构数据",
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_systemmenu.RespSystemMenuTree"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/menus/update": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "更新菜单管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "更新菜单管理",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_systemmenu.ReqSystemMenuUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_systemmenu.RespSystemMenuItem"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/orgs/create": {
            "post": {
                "description": "创建组织机构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "创建组织机构",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_systemorg.ReqSystemOrgCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_systemorg.RespSystemOrgDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/orgs/delete": {
            "post": {
                "description": "删除组织机构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "删除组织机构",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_systemorg.ReqSystemOrgId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/orgs/tree": {
            "get": {
                "description": "获取组织机构树结构数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "获取组织机构树结构数据",
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_systemorg.RespSystemOrgTree"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/system/orgs/update": {
            "post": {
                "description": "更新组织机构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "更新组织机构",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_systemorg.ReqSystemOrgUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code不为0时表示有错误",
                        "schema": {
                            "$ref": "#/definitions/goal-app_pkg_render.JsonDataResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "admin_accountuser.ReqCreateUser": {
            "type": "object",
            "required": [
                "password",
                "password_confirm",
                "phone"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "abc@a.com"
                },
                "is_admin": {
                    "description": "是否属于管理员账号",
                    "type": "boolean",
                    "example": true
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "example": "Tom"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "password_confirm": {
                    "description": "确认密码",
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "admin_accountuser.ReqUpdateUser": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "用户头像URL",
                    "type": "string",
                    "example": "a/b/c.jpg"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "abc@abc.com"
                },
                "gender": {
                    "description": "性别:3-保密,1-男,2-女",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.UserGender"
                        }
                    ],
                    "example": 3
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "example": "Tom"
                },
                "signature": {
                    "description": "个性化签名",
                    "type": "string",
                    "example": "haha"
                },
                "status": {
                    "description": "用户状态",
                    "type": "string",
                    "example": "FREEZE"
                }
            }
        },
        "admin_accountuser.RespUserDetail": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "账号创建时间(unix秒时间戳)",
                    "type": "integer",
                    "example": 1724914598
                },
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "abc@abc.com"
                },
                "is_admin": {
                    "description": "是否管理员",
                    "type": "boolean",
                    "example": false
                },
                "last_login_time": {
                    "description": "最近登录时间(unix秒时间戳)",
                    "type": "integer",
                    "example": 1724914598
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "example": "Tom"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                },
                "status": {
                    "description": "用户状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.UserStatusType"
                        }
                    ],
                    "example": "ACTIVE"
                },
                "uuid": {
                    "description": "用户UUID,32位字符串",
                    "type": "string",
                    "example": "826d6b1aa64d471d822d667e92218158"
                }
            }
        },
        "admin_auth.ReqAdminAuth": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "admin_auth.RespAdminAuth": {
            "type": "object",
            "properties": {
                "expire_time": {
                    "description": "过期时间",
                    "type": "string"
                },
                "token": {
                    "description": "令牌",
                    "type": "string"
                },
                "user": {
                    "description": "用户基本信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/admin_auth.RespAdminAuthUser"
                        }
                    ]
                }
            }
        },
        "admin_auth.RespAdminAuthUser": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "last_login_time": {
                    "description": "最近的登录时间(unix秒时间戳)",
                    "type": "integer",
                    "example": 1724914598
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "带掩码的手机号",
                    "type": "string",
                    "example": "138****8000"
                },
                "uuid": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "admin_generator.ReqDelGenTableColumn": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "description": "主键",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "admin_generator.ReqDelTable": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "description": "主键",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "admin_generator.ReqGenTableCreate": {
            "type": "object",
            "required": [
                "tables"
            ],
            "properties": {
                "tables": {
                    "description": "导入的表, 用\",\"分隔",
                    "type": "string"
                }
            }
        },
        "admin_generator.ReqPreview": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "主键",
                    "type": "integer"
                }
            }
        },
        "admin_generator.RespDbTable": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "name": {
                    "description": "表名称",
                    "type": "string"
                },
                "table_comment": {
                    "description": "表描述",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "admin_generator.RespGenColumn": {
            "type": "object",
            "properties": {
                "column_comment": {
                    "description": "字段描述",
                    "type": "string"
                },
                "column_length": {
                    "description": "字段长度",
                    "type": "integer"
                },
                "column_name": {
                    "description": "字段名称",
                    "type": "string"
                },
                "column_type": {
                    "description": "字段类型",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "dict_type": {
                    "description": "字典类型",
                    "type": "string"
                },
                "go_field": {
                    "description": "Go字段",
                    "type": "string"
                },
                "go_type": {
                    "description": "Go类型",
                    "type": "string"
                },
                "html_type": {
                    "description": "显示类型: [文本框、文本域、下拉框、复选框、单选框、日期控件]",
                    "type": "string"
                },
                "id": {
                    "description": "字段主键",
                    "type": "integer"
                },
                "is_edit": {
                    "description": "是否编辑字段",
                    "type": "integer"
                },
                "is_insert": {
                    "description": "是否为插入字段",
                    "type": "integer"
                },
                "is_list": {
                    "description": "是否列表字段",
                    "type": "integer"
                },
                "is_query": {
                    "description": "是否查询字段",
                    "type": "integer"
                },
                "is_required": {
                    "description": "是否必填",
                    "type": "integer"
                },
                "query_type": {
                    "description": "查询方式: [等于、不等于、大于、小于、范围]",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "admin_generator.RespGenTableItem": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "entity_name": {
                    "description": "实体的名称",
                    "type": "string"
                },
                "function_name": {
                    "description": "生成功能名",
                    "type": "string"
                },
                "gen_path": {
                    "description": "生成代码路径: [不填默认项目路径]",
                    "type": "string"
                },
                "gen_tpl": {
                    "description": "生成模板方式: [crud=单表, tree=树表]",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "module_name": {
                    "description": "'生成模块名",
                    "type": "string"
                },
                "name": {
                    "description": "表名称",
                    "type": "string"
                },
                "table_comment": {
                    "description": "表描述",
                    "type": "string"
                },
                "tree_name": {
                    "description": "树显示字段",
                    "type": "string"
                },
                "tree_parent": {
                    "description": "树父级字段",
                    "type": "string"
                },
                "tree_primary": {
                    "description": "树主键字段",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                }
            }
        },
        "admin_generator.RespPreviewItem": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "admin_systemconfig.ReqSystemConfigCreate": {
            "type": "object",
            "properties": {
                "desc": {
                    "description": "配置说明",
                    "type": "string"
                },
                "enabled": {
                    "description": "是否启用,0-否,1-是",
                    "type": "integer"
                },
                "name": {
                    "description": "配置名称",
                    "type": "string"
                },
                "scope": {
                    "description": "作用域,global-全局,admin-管理后台,app-前台应用",
                    "type": "string"
                },
                "value": {
                    "description": "配置值",
                    "type": "string"
                }
            }
        },
        "admin_systemconfig.ReqSystemConfigUpdate": {
            "type": "object",
            "properties": {
                "desc": {
                    "description": "配置说明",
                    "type": "string"
                },
                "enabled": {
                    "description": "是否启用,0-否,1-是",
                    "type": "integer"
                },
                "id": {
                    "description": "流水ID",
                    "type": "integer"
                },
                "name": {
                    "description": "配置名称",
                    "type": "string"
                },
                "scope": {
                    "description": "作用域,global-全局,admin-管理后台,app-前台应用",
                    "type": "string"
                },
                "value": {
                    "description": "配置值",
                    "type": "string"
                }
            }
        },
        "admin_systemconfig.RespSystemConfigItem": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "数据创建时间",
                    "type": "integer"
                },
                "desc": {
                    "description": "配置说明",
                    "type": "string"
                },
                "enabled": {
                    "description": "是否启用,0-否,1-是",
                    "type": "integer"
                },
                "id": {
                    "description": "流水ID",
                    "type": "integer"
                },
                "name": {
                    "description": "配置名称",
                    "type": "string"
                },
                "scope": {
                    "description": "作用域,global-全局,admin-管理后台,app-前台应用",
                    "type": "string"
                },
                "update_time": {
                    "description": "数据更新时间",
                    "type": "integer"
                },
                "value": {
                    "description": "配置值",
                    "type": "string"
                }
            }
        },
        "admin_systemmenu.ReqSystemMenuCreate": {
            "type": "object",
            "properties": {
                "auth_tag": {
                    "description": "'权限标识'",
                    "type": "string"
                },
                "component": {
                    "description": "'前端组件'",
                    "type": "string"
                },
                "icon": {
                    "description": "'菜单图标'",
                    "type": "string"
                },
                "kind": {
                    "description": "'权限类型: dir=目录，menu=菜单，button=按钮''",
                    "type": "string"
                },
                "name": {
                    "description": "'菜单名称'",
                    "type": "string"
                },
                "params": {
                    "description": "'路由参数'",
                    "type": "string"
                },
                "parent_id": {
                    "description": "'上级菜单ID'",
                    "type": "integer"
                },
                "route": {
                    "description": "'路由地址'",
                    "type": "string"
                },
                "sort": {
                    "description": "'菜单排序'",
                    "type": "integer"
                },
                "status": {
                    "description": "'状态: disable=停用, enable=启用'",
                    "type": "string"
                }
            }
        },
        "admin_systemmenu.ReqSystemMenuUpdate": {
            "type": "object",
            "properties": {
                "auth_tag": {
                    "description": "'权限标识'",
                    "type": "string"
                },
                "component": {
                    "description": "'前端组件'",
                    "type": "string"
                },
                "icon": {
                    "description": "'菜单图标'",
                    "type": "string"
                },
                "id": {
                    "description": "流水ID",
                    "type": "integer"
                },
                "kind": {
                    "description": "'权限类型: dir=目录，menu=菜单，button=按钮''",
                    "type": "string"
                },
                "name": {
                    "description": "'菜单名称'",
                    "type": "string"
                },
                "params": {
                    "description": "'路由参数'",
                    "type": "string"
                },
                "parent_id": {
                    "description": "'上级菜单ID'",
                    "type": "integer"
                },
                "route": {
                    "description": "'路由地址'",
                    "type": "string"
                },
                "sort": {
                    "description": "'菜单排序'",
                    "type": "integer"
                },
                "status": {
                    "description": "'状态: disable=停用, enable=启用'",
                    "type": "string"
                }
            }
        },
        "admin_systemmenu.RespSystemMenuItem": {
            "type": "object",
            "properties": {
                "auth_tag": {
                    "description": "'权限标识'",
                    "type": "string"
                },
                "component": {
                    "description": "'前端组件'",
                    "type": "string"
                },
                "create_time": {
                    "description": "数据创建时间",
                    "type": "integer"
                },
                "icon": {
                    "description": "'菜单图标'",
                    "type": "string"
                },
                "id": {
                    "description": "流水ID",
                    "type": "integer"
                },
                "kind": {
                    "description": "'权限类型: dir=目录，menu=菜单，button=按钮''",
                    "type": "string"
                },
                "name": {
                    "description": "'菜单名称'",
                    "type": "string"
                },
                "params": {
                    "description": "'路由参数'",
                    "type": "string"
                },
                "parent_id": {
                    "description": "'上级菜单ID'",
                    "type": "integer"
                },
                "route": {
                    "description": "'路由地址'",
                    "type": "string"
                },
                "sort": {
                    "description": "'菜单排序'",
                    "type": "integer"
                },
                "status": {
                    "description": "'状态: disable=停用, enable=启用'",
                    "type": "string"
                },
                "update_time": {
                    "description": "数据更新时间",
                    "type": "integer"
                }
            }
        },
        "admin_systemmenu.RespSystemMenuTree": {
            "type": "object",
            "properties": {
                "auth_tag": {
                    "description": "'权限标识'",
                    "type": "string"
                },
                "children": {
                    "description": "子节点",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_systemmenu.RespSystemMenuTree"
                    }
                },
                "component": {
                    "description": "'前端组件'",
                    "type": "string"
                },
                "create_time": {
                    "description": "数据创建时间",
                    "type": "integer"
                },
                "icon": {
                    "description": "'菜单图标'",
                    "type": "string"
                },
                "id": {
                    "description": "流水ID",
                    "type": "integer"
                },
                "kind": {
                    "description": "'权限类型: dir=目录，menu=菜单，button=按钮''",
                    "type": "string"
                },
                "name": {
                    "description": "'菜单名称'",
                    "type": "string"
                },
                "params": {
                    "description": "'路由参数'",
                    "type": "string"
                },
                "parent_id": {
                    "description": "'上级菜单ID'",
                    "type": "integer"
                },
                "parent_name": {
                    "description": "'父级名称'",
                    "type": "string"
                },
                "route": {
                    "description": "'路由地址'",
                    "type": "string"
                },
                "sort": {
                    "description": "'菜单排序'",
                    "type": "integer"
                },
                "status": {
                    "description": "'状态: disable=停用, enable=启用'",
                    "type": "string"
                },
                "update_time": {
                    "description": "数据更新时间",
                    "type": "integer"
                }
            }
        },
        "admin_systemorg.ReqSystemOrgCreate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "manager": {
                    "description": "负责人名称",
                    "type": "string"
                },
                "name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父ID",
                    "type": "integer",
                    "minimum": 0
                },
                "phone": {
                    "description": "负责人电话",
                    "type": "string"
                }
            }
        },
        "admin_systemorg.ReqSystemOrgId": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "组织ID",
                    "type": "integer"
                }
            }
        },
        "admin_systemorg.ReqSystemOrgUpdate": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "description": "组织ID",
                    "type": "integer"
                },
                "manager": {
                    "description": "负责人名称",
                    "type": "string"
                },
                "name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父ID",
                    "type": "integer",
                    "minimum": 0
                },
                "phone": {
                    "description": "负责人电话",
                    "type": "string"
                }
            }
        },
        "admin_systemorg.RespSystemOrgDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "组织ID",
                    "type": "integer"
                },
                "manager": {
                    "description": "负责人名称",
                    "type": "string"
                },
                "name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父ID",
                    "type": "integer"
                },
                "parent_name": {
                    "description": "父名称",
                    "type": "string"
                },
                "phone": {
                    "description": "负责人电话",
                    "type": "string"
                }
            }
        },
        "admin_systemorg.RespSystemOrgTree": {
            "type": "object",
            "properties": {
                "children": {
                    "description": "子节点",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_systemorg.RespSystemOrgTree"
                    }
                },
                "id": {
                    "description": "组织ID",
                    "type": "integer"
                },
                "manager": {
                    "description": "负责人名称",
                    "type": "string"
                },
                "name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父ID",
                    "type": "integer"
                },
                "parent_name": {
                    "description": "父名称",
                    "type": "string"
                },
                "phone": {
                    "description": "负责人电话",
                    "type": "string"
                }
            }
        },
        "goal-app_pkg_render.JsonDataResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "goal-app_pkg_render.RespPageJson": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "result": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.UserGender": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "UserGenderMale",
                "UserGenderFemale",
                "UserGenderUnknown"
            ]
        },
        "model.UserStatusType": {
            "type": "string",
            "enum": [
                "INACTIVE",
                "ACTIVE",
                "FREEZE",
                "DELETE"
            ],
            "x-enum-varnames": [
                "UserStatusInactive",
                "UserStatusActive",
                "UserStatusFreeze",
                "UserStatusDelete"
            ]
        }
    },
    "securityDefinitions": {
        "AdminAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "后台管理系统接口文档",
	Description:      "http状态码是200，code为0时表示正常返回；code不为0时表示有业务错误。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
