basePath: /api/v1
definitions:
  model.UserStatusType:
    enum:
    - INACTIVE
    - ACTIVE
    - FREEZE
    - DELETE
    type: string
    x-enum-varnames:
    - UserStatusInactive
    - UserStatusActive
    - UserStatusFreeze
    - UserStatusDelete
  types.ReqAdminAuth:
    properties:
      password:
        description: 密码
        example: "123456"
        type: string
      phone:
        description: 手机号
        example: "13800138000"
        type: string
    required:
    - password
    - phone
    type: object
  types.ReqCreateUser:
    properties:
      email:
        description: 邮箱
        example: abc@a.com
        type: string
      nickname:
        description: 昵称
        example: Tom
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      password_confirm:
        description: 确认密码
        example: "123456"
        type: string
      phone:
        description: 手机号
        example: "13800138000"
        type: string
    required:
    - password
    - password_confirm
    - phone
    type: object
  types.ReqGetHistoryList:
    properties:
      created_at_start:
        description: 数据创建时间起始
        example: "2023-09-01 01:30:59"
        type: string
      email:
        description: 用户邮箱
        example: abc@abc.com
        type: string
      last_login_at_end:
        description: 数据创建时间截止
        example: "2023-09-01 22:59:59"
        type: string
      limit:
        default: 10
        description: 每页数量
        example: 10
        type: integer
      nickname:
        description: 用户昵称
        example: Tom
        type: string
      page:
        default: 1
        description: 页码
        example: 1
        type: integer
      phone:
        description: 用户手机号
        example: "13800138000"
        type: string
      user_id:
        description: 用户ID
        example: 123
        type: integer
      user_uuid:
        description: 用户UUID
        example: abcef123
        type: string
    type: object
  types.ReqGetUserList:
    properties:
      created_at_start:
        description: 数据创建时间起始
        example: "2023-09-01 01:30:59"
        type: string
      email:
        description: 邮箱,模糊查旬
        example: abc@abc.com
        type: string
      last_login_at_end:
        description: 最近登录时间截止
        example: "2023-09-01 22:59:59"
        type: string
      last_login_at_start:
        description: 最近登录时间起始
        example: "2023-09-01 01:30:59"
        type: string
      limit:
        default: 10
        description: 每页数量
        example: 10
        type: integer
      nickname:
        description: 昵称,模糊查询
        example: Tom
        type: string
      page:
        default: 1
        description: 页码
        example: 1
        type: integer
      phone:
        description: 手机号,模糊查询
        example: "13800138000"
        type: string
      status:
        description: 用户状态,多种状态过滤使用逗号分隔
        example:
        - FREEZE
        - ACTIVE
        items:
          $ref: '#/definitions/model.UserStatusType'
        type: array
    type: object
  types.ReqUpdateUser:
    properties:
      avatar:
        description: 用户头像URL
        example: a/b/c.jpg
        type: string
      email:
        description: 邮箱
        example: abc@abc.com
        type: string
      gender:
        description: 性别:3-保密,1-男,2-女
        example: 3
        type: integer
      nickname:
        description: 昵称
        example: Tom
        type: string
      signature:
        description: 个性化签名
        example: haha
        type: string
      status:
        description: 用户状态
        example: FREEZE
        type: string
    type: object
  types.RespAdminAuth:
    properties:
      expire_time:
        description: 过期时间
        type: string
      token:
        description: 令牌
        type: string
      user:
        allOf:
        - $ref: '#/definitions/types.RespAdminAuthUser'
        description: 用户基本信息
    type: object
  types.RespAdminAuthUser:
    properties:
      last_login_at:
        description: 最近的登录时间
        type: string
      phone:
        description: 带掩码的手机号
        example: 138****8000
        type: string
      uuid:
        description: 用户uuid
        type: string
    type: object
  types.RespEmptyJson:
    properties:
      code:
        description: 结果码：0-成功，其它-失败
        example: 0
        type: integer
      msg:
        description: 消息, code不为0时，返回简单的错误描述
        example: ok
        type: string
    type: object
  types.RespFailJson:
    properties:
      code:
        description: 结果码：0-成功，其它-失败
        example: 1000
        type: integer
      error:
        description: 具体的错误信息
        example: not found
        type: string
      msg:
        description: 消息, code不为0时，返回简单的错误描述
        example: error
        type: string
    type: object
  types.RespUserDetail:
    properties:
      is_admin:
        description: 是否管理员
        example: false
        type: boolean
      last_login_at:
        description: 最近登录时间
        example: "2023-09-01 13:30:59"
        type: string
      nickname:
        description: 昵称
        example: Tom
        type: string
      phone:
        description: 手机号
        example: "13800138000"
        type: string
      status:
        allOf:
        - $ref: '#/definitions/model.UserStatusType'
        description: 用户状态
        example: ACTIVE
      uuid:
        description: 用户UUID,32位字符串
        example: 826d6b1aa64d471d822d667e92218158
        type: string
    type: object
info:
  contact: {}
  description: http状态码是200，code为0时表示正常返回；code不为0时表示有业务错误。返回的JSON数据结构如下：
  title: 后台管理系统接口文档
  version: "1.0"
paths:
  /account/history/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取用户登录历史记录列表
      parameters:
      - description: 数据创建时间起始
        example: "2023-09-01 01:30:59"
        in: query
        name: created_at_start
        type: string
      - description: 用户邮箱
        example: abc@abc.com
        in: query
        name: email
        type: string
      - description: 数据创建时间截止
        example: "2023-09-01 22:59:59"
        in: query
        name: last_login_at_end
        type: string
      - default: 10
        description: 每页数量
        example: 10
        in: query
        name: limit
        type: integer
      - description: 用户昵称
        example: Tom
        in: query
        name: nickname
        type: string
      - default: 1
        description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 用户手机号
        example: "13800138000"
        in: query
        name: phone
        type: string
      - description: 用户ID
        example: 123
        in: query
        name: user_id
        type: integer
      - description: 用户UUID
        example: abcef123
        in: query
        name: user_uuid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ReqGetHistoryList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.RespFailJson'
      security:
      - ApiKeyAuth: []
      summary: 登录历史记录列表
      tags:
      - 用户管理
  /account/login:
    post:
      consumes:
      - application/json
      description: 后台管理系统登录接口
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.ReqAdminAuth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RespAdminAuth'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.RespFailJson'
      summary: 登录
      tags:
      - 登录退出
  /account/logout:
    post:
      description: |-
        退出后台管理系统
        前端调用该接口，无需关注结果，自行清理掉请求头的 Authorization，页面跳转至首页
        后端可以执行清理redis缓存, 设置token黑名单等操作
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RespEmptyJson'
      security:
      - ApiKeyAuth: []
      summary: 退出
      tags:
      - 登录退出
  /account/user/create:
    post:
      consumes:
      - application/json
      description: 创建新用户
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.ReqCreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RespUserDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.RespFailJson'
      security:
      - ApiKeyAuth: []
      summary: 创建用户
      tags:
      - 用户管理
  /account/user/delete:
    post:
      consumes:
      - application/json
      description: 删除单个用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RespEmptyJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.RespFailJson'
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - 用户管理
  /account/user/detail:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取用户详情
      parameters:
      - description: 用户UUID
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RespUserDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.RespFailJson'
      security:
      - ApiKeyAuth: []
      summary: 通过用户UUID获取用户详情
      tags:
      - 用户管理
  /account/user/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取用户列表
      parameters:
      - description: 数据创建时间起始
        example: "2023-09-01 01:30:59"
        in: query
        name: created_at_start
        type: string
      - description: 邮箱,模糊查旬
        example: abc@abc.com
        in: query
        name: email
        type: string
      - description: 最近登录时间截止
        example: "2023-09-01 22:59:59"
        in: query
        name: last_login_at_end
        type: string
      - description: 最近登录时间起始
        example: "2023-09-01 01:30:59"
        in: query
        name: last_login_at_start
        type: string
      - default: 10
        description: 每页数量
        example: 10
        in: query
        name: limit
        type: integer
      - description: 昵称,模糊查询
        example: Tom
        in: query
        name: nickname
        type: string
      - default: 1
        description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 手机号,模糊查询
        example: "13800138000"
        in: query
        name: phone
        type: string
      - collectionFormat: multi
        description: 用户状态,多种状态过滤使用逗号分隔
        example:
        - FREEZE
        - ACTIVE
        in: query
        items:
          enum:
          - INACTIVE
          - ACTIVE
          - FREEZE
          - DELETE
          type: string
        name: status
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ReqGetUserList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.RespFailJson'
      security:
      - ApiKeyAuth: []
      summary: 获取用户列表
      tags:
      - 用户管理
  /account/user/update:
    post:
      consumes:
      - application/json
      description: 更新用户数据
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.ReqUpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RespEmptyJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.RespFailJson'
      security:
      - ApiKeyAuth: []
      summary: 更新用户
      tags:
      - 用户管理
securityDefinitions:
  ApiKeyAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
