basePath: /api/v1
definitions:
  admin_accounhistory.ReqGetHistoryList:
    properties:
      created_at_end:
        description: 数据创建结束区间
        type: integer
      created_at_start:
        description: 数据创建开始区间
        type: integer
      email:
        description: 用户邮箱
        example: abc@abc.com
        type: string
      limit:
        default: 10
        description: 每页数量
        example: 10
        type: integer
      nickname:
        description: 用户昵称
        example: Tom
        type: string
      page:
        default: 1
        description: 页码
        example: 1
        type: integer
      phone:
        description: 用户手机号
        example: "13800138000"
        type: string
      user_id:
        description: 用户ID
        example: 123
        type: integer
      user_uuid:
        description: 用户UUID
        example: abcef123
        type: string
    type: object
  admin_accountuser.ReqCreateUser:
    properties:
      email:
        description: 邮箱
        example: abc@a.com
        type: string
      is_admin:
        description: 是否属于管理员账号
        example: true
        type: boolean
      nickname:
        description: 昵称
        example: Tom
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      password_confirm:
        description: 确认密码
        example: "123456"
        type: string
      phone:
        description: 手机号
        example: "13800138000"
        type: string
    required:
    - password
    - password_confirm
    - phone
    type: object
  admin_accountuser.ReqUpdateUser:
    properties:
      avatar:
        description: 用户头像URL
        example: a/b/c.jpg
        type: string
      email:
        description: 邮箱
        example: abc@abc.com
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/model.UserGender'
        description: 性别:3-保密,1-男,2-女
        example: 3
      nickname:
        description: 昵称
        example: Tom
        type: string
      signature:
        description: 个性化签名
        example: haha
        type: string
      status:
        description: 用户状态
        example: FREEZE
        type: string
    type: object
  admin_accountuser.RespGetUserList:
    properties:
      limit:
        type: integer
      page:
        type: integer
      result: {}
      total:
        type: integer
    type: object
  admin_accountuser.RespUserDetail:
    properties:
      created_at:
        description: 账号创建时间(unix秒时间戳)
        example: 1724914598
        type: integer
      email:
        description: 邮箱
        example: abc@abc.com
        type: string
      is_admin:
        description: 是否管理员
        example: false
        type: boolean
      last_login_at:
        description: 最近登录时间(unix秒时间戳)
        example: 1724914598
        type: integer
      nickname:
        description: 昵称
        example: Tom
        type: string
      phone:
        description: 手机号
        example: "13800138000"
        type: string
      status:
        allOf:
        - $ref: '#/definitions/model.UserStatusType'
        description: 用户状态
        example: ACTIVE
      uuid:
        description: 用户UUID,32位字符串
        example: 826d6b1aa64d471d822d667e92218158
        type: string
    type: object
  admin_auth.ReqAdminAuth:
    properties:
      password:
        description: 密码
        example: "123456"
        type: string
      phone:
        description: 手机号
        example: "13800138000"
        type: string
    required:
    - password
    - phone
    type: object
  admin_auth.RespAdminAuth:
    properties:
      expire_time:
        description: 过期时间
        type: string
      token:
        description: 令牌
        type: string
      user:
        allOf:
        - $ref: '#/definitions/admin_auth.RespAdminAuthUser'
        description: 用户基本信息
    type: object
  admin_auth.RespAdminAuthUser:
    properties:
      avatar:
        description: 头像
        type: string
      last_login_at:
        description: 最近的登录时间(unix秒时间戳)
        example: 1724914598
        type: integer
      nickname:
        description: 昵称
        type: string
      phone:
        description: 带掩码的手机号
        example: 138****8000
        type: string
      uuid:
        description: 用户uuid
        type: string
    type: object
  goal-app_pkg_render.JsonDataResp:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.UserGender:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - UserGenderMale
    - UserGenderFemale
    - UserGenderUnknown
  model.UserStatusType:
    enum:
    - INACTIVE
    - ACTIVE
    - FREEZE
    - DELETE
    type: string
    x-enum-varnames:
    - UserStatusInactive
    - UserStatusActive
    - UserStatusFreeze
    - UserStatusDelete
info:
  contact: {}
  description: http状态码是200，code为0时表示正常返回；code不为0时表示有业务错误。
  title: 后台管理系统接口文档
  version: "1.0"
paths:
  /account/history/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取用户登录历史记录列表
      parameters:
      - description: 数据创建结束区间
        in: query
        name: created_at_end
        type: integer
      - description: 数据创建开始区间
        in: query
        name: created_at_start
        type: integer
      - description: 用户邮箱
        example: abc@abc.com
        in: query
        name: email
        type: string
      - default: 10
        description: 每页数量
        example: 10
        in: query
        name: limit
        type: integer
      - description: 用户昵称
        example: Tom
        in: query
        name: nickname
        type: string
      - default: 1
        description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 用户手机号
        example: "13800138000"
        in: query
        name: phone
        type: string
      - description: 用户ID
        example: 123
        in: query
        name: user_id
        type: integer
      - description: 用户UUID
        example: abcef123
        in: query
        name: user_uuid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin_accounhistory.ReqGetHistoryList'
        "500":
          description: Internal Server Error
      security:
      - AdminAuth: []
      summary: 登录历史记录列表
      tags:
      - 用户管理
  /account/login:
    post:
      consumes:
      - application/json
      description: 后台管理系统登录接口
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin_auth.ReqAdminAuth'
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
            - properties:
                data:
                  $ref: '#/definitions/admin_auth.RespAdminAuth'
              type: object
        "500":
          description: Internal Server Error
      summary: 登录
      tags:
      - 登录退出
  /account/logout:
    post:
      description: |-
        退出后台管理系统
        前端调用该接口，无需关注结果，自行清理掉请求头的 Authorization，页面跳转至首页
        后端可以执行清理redis缓存, 设置token黑名单等操作
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
      security:
      - AdminAuth: []
      summary: 退出
      tags:
      - 登录退出
  /account/user/{uuid}/profile:
    get:
      description: 用户个人资料
      parameters:
      - description: 用户UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
      security:
      - AdminAuth: []
      summary: 用户个人资料
      tags:
      - 用户管理
  /account/user/create:
    post:
      consumes:
      - application/json
      description: 创建新用户
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin_accountuser.ReqCreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示错误
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
            - properties:
                data:
                  $ref: '#/definitions/admin_accountuser.RespUserDetail'
              type: object
        "500":
          description: Internal Server Error
      security:
      - AdminAuth: []
      summary: 创建用户
      tags:
      - 用户管理
  /account/user/delete:
    post:
      consumes:
      - application/json
      description: 删除单个用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
      security:
      - AdminAuth: []
      summary: 删除用户
      tags:
      - 用户管理
  /account/user/detail:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取用户详情
      parameters:
      - description: 用户UUID
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin_accountuser.RespUserDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
      security:
      - AdminAuth: []
      summary: 通过用户UUID获取用户详情
      tags:
      - 用户管理
  /account/user/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取用户列表
      parameters:
      - description: 数据创建结束区间
        in: query
        name: created_at_end
        type: integer
      - description: 数据创建开始区间
        in: query
        name: created_at_start
        type: integer
      - description: 邮箱,模糊查询
        example: abc@abc.com
        in: query
        name: email
        type: string
      - description: 是否admin, 1 or 0
        example: 1
        in: query
        name: is_admin
        type: integer
      - description: 最近登录结束时间
        in: query
        name: last_login_at_end
        type: integer
      - description: 最近登录开始时间
        in: query
        name: last_login_at_start
        type: integer
      - default: 10
        description: 每页数量
        example: 10
        in: query
        name: limit
        type: integer
      - description: 昵称,模糊查询
        example: Tom
        in: query
        name: nickname
        type: string
      - default: 1
        description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 手机号,模糊查询
        example: "13800138000"
        in: query
        name: phone
        type: string
      - collectionFormat: multi
        description: 用户状态
        example:
        - FREEZE
        - ACTIVE
        in: query
        items:
          enum:
          - INACTIVE
          - ACTIVE
          - FREEZE
          - DELETE
          type: string
        name: status[]
        type: array
      - description: 用户UUID,精确匹配
        example: 826d6b1aa64d471d822d667e92218158
        in: query
        name: uuid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/admin_accountuser.RespGetUserList'
                  - properties:
                      result:
                        items:
                          $ref: '#/definitions/admin_accountuser.RespUserDetail'
                        type: array
                    type: object
              type: object
        "500":
          description: Internal Server Error
      security:
      - AdminAuth: []
      summary: 获取用户列表
      tags:
      - 用户管理
  /account/user/update:
    post:
      consumes:
      - application/json
      description: 更新用户数据
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin_accountuser.ReqUpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
      security:
      - AdminAuth: []
      summary: 更新用户
      tags:
      - 用户管理
  /account/users/{uuid}/profile/update:
    post:
      consumes:
      - application/json
      description: 更新用户个人资料
      parameters:
      - description: 用户UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.JsonDataResp'
      security:
      - AdminAuth: []
      summary: 删除用户
      tags:
      - 用户管理
securityDefinitions:
  AdminAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
