basePath: /api/v1
definitions:
  api_attachment.AttachmentResp:
    properties:
      created_at:
        description: 上传时间
        type: string
      name:
        description: 文件名
        type: string
      size:
        description: '文件大小, 单位: 字节'
        type: integer
      uuid:
        description: 文件UUID
        type: string
    type: object
  api_auth.ReqAuthSignup:
    properties:
      captcha_answer:
        description: 验证码,4位
        maxLength: 6
        minLength: 6
        type: string
      captcha_id:
        description: 验证码ID
        type: string
      confirm_password:
        description: 确认密码
        example: "123456"
        type: string
      email:
        description: Phone    string `json:"phone" binding:"required" example:"13800138000"`
          // 手机号
        example: foo@bar.com
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
    required:
    - captcha_answer
    - captcha_id
    - confirm_password
    - password
    type: object
  api_auth.ReqUserAuth:
    properties:
      captcha_answer:
        description: 验证码,4位
        maxLength: 6
        minLength: 6
        type: string
      captcha_id:
        description: 验证码ID
        type: string
      email:
        description: Phone    string `json:"phone" binding:"required" example:"13800138000"`
          // 手机号
        example: foo@bar.com
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
    required:
    - captcha_answer
    - captcha_id
    - email
    - password
    type: object
  api_auth.RespAuthCaptcha:
    properties:
      captcha_id:
        description: 验证码ID
        type: string
      captcha_img:
        description: base64编码的验证码图片
        type: string
    type: object
  api_auth.RespUserAuth:
    properties:
      expire_time:
        description: 过期时间
        type: string
      token:
        description: 令牌
        type: string
      user:
        allOf:
        - $ref: '#/definitions/api_auth.RespUserInfo'
        description: 用户基本信息
    type: object
  api_auth.RespUserInfo:
    properties:
      avatar:
        description: 头像
        type: string
      email:
        description: 邮箱
        example: foo@bar.com
        type: string
      last_login_at:
        description: 最近的登录时间
        type: string
      nickname:
        description: 昵称
        type: string
      phone:
        description: 带掩码的手机号
        example: 138****8000
        type: string
      uuid:
        description: 用户uuid
        type: string
    type: object
  api_imageflix.CreditReduceReq:
    properties:
      point:
        description: 使用点数
        type: integer
    required:
    - point
    type: object
  api_imageflix.JobStartReq:
    properties:
      job_id:
        description: 任务ID
        type: integer
    required:
    - job_id
    type: object
  api_imageflix.UserCreditResp:
    properties:
      usable:
        description: 可用点数
        type: integer
    type: object
  api_user.ReqUpdateUser:
    properties:
      avatar:
        description: 用户头像URL
        example: a/b/c.jpg
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/model.UserGender'
        description: 性别:3-保密,1-男,2-女
        example: 3
      nickname:
        description: 昵称
        example: Tom
        type: string
      signature:
        description: 个性化签名
        example: haha
        type: string
      uuid:
        description: 用户UUID
        type: string
    type: object
  api_user.ReqUpdateUserPassword:
    properties:
      new_password:
        description: 新密码
        type: string
      old_password:
        description: 旧密码
        type: string
      uuid:
        description: 用户UUID
        type: string
    type: object
  api_user.ReqUpdateUserProfile:
    properties:
      id_number:
        description: 身份证号
        type: string
      real_name:
        description: 真实姓名
        type: string
      user_id:
        description: 用户ID
        type: integer
    type: object
  api_user.RespUserInfo:
    properties:
      avatar:
        description: 头像
        type: string
      last_login_at:
        description: 最近的登录时间
        type: string
      nickname:
        description: 昵称
        type: string
      phone:
        description: 带掩码的手机号
        example: 138****8000
        type: string
      uuid:
        description: 用户uuid
        type: string
    type: object
  goal-app_pkg_render.RespJsonData:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.UserGender:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - UserGenderMale
    - UserGenderFemale
    - UserGenderUnknown
info:
  contact: {}
  description: http状态码是200，code为0时表示正常返回；code不为0时表示有业务错误。
  title: 前台接口文档
  version: "1.0"
paths:
  /attachments:
    post:
      consumes:
      - multipart/form-data
      description: 用户上传附件
      parameters:
      - description: 文件流
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: http状态码是200，并且code是200, 表示正常返回；code不是200时表示有业务错误
          schema:
            $ref: '#/definitions/api_attachment.AttachmentResp'
      security:
      - ApiKeyAuth: []
      summary: 新增附件
      tags:
      - 通用
  /auth/captcha:
    get:
      description: 获取验证码ID和图片base64
      parameters:
      - default: 32
        description: 高
        example: 32
        in: query
        name: h
        type: integer
      - description: 时间戳字符串，避免缓存
        in: query
        name: ts
        type: string
      - default: 128
        description: 宽
        example: 128
        in: query
        name: w
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
            - properties:
                data:
                  $ref: '#/definitions/api_auth.RespAuthCaptcha'
              type: object
        "500":
          description: Internal Server Error
      summary: 获取验证码ID和图片base64
      tags:
      - 通用
  /auth/logout:
    post:
      description: |-
        前台用户退出
        前端调用该接口，无需关注结果，自行清理掉请求头的 Authorization，页面跳转至首页
        后端可以执行清理redis缓存, 设置token黑名单等操作
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "500":
          description: Internal Server Error
      security:
      - APIAuth: []
      summary: 退出
      tags:
      - 登录认证
  /auth/signin:
    post:
      consumes:
      - application/json
      description: 前台用户登录接口
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api_auth.ReqUserAuth'
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
            - properties:
                data:
                  $ref: '#/definitions/api_auth.RespUserAuth'
              type: object
        "500":
          description: Internal Server Error
      summary: 登录
      tags:
      - 登录认证
  /auth/signup:
    post:
      consumes:
      - application/json
      description: 前台用户注册接口
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api_auth.ReqAuthSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "500":
          description: Internal Server Error
      summary: 注册
      tags:
      - 登录认证
  /create:
    post:
      description: 当前登录用户上传图片任务
      parameters:
      - description: 文件流
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "500":
          description: Internal Server Error
      security:
      - APIAuth: []
      summary: 当前登录用户上传图片任务
      tags:
      - ImageFlix-任务
  /reduce:
    post:
      description: 获取当前登录用户可用资源包余额
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api_imageflix.CreditReduceReq'
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "500":
          description: Internal Server Error
      security:
      - APIAuth: []
      summary: 获取当前登录用户可用资源包余额
      tags:
      - ImageFlix-资源包
  /start:
    post:
      description: 当前登录用户出发开始任务，成功后扣除点数
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api_imageflix.JobStartReq'
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "500":
          description: Internal Server Error
      security:
      - APIAuth: []
      summary: 当前登录用户出发开始任务
      tags:
      - ImageFlix-任务
  /usable:
    get:
      description: 获取当前登录用户可用资源包余额
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
            - properties:
                data:
                  $ref: '#/definitions/api_imageflix.UserCreditResp'
              type: object
        "500":
          description: Internal Server Error
      security:
      - APIAuth: []
      summary: 获取当前登录用户可用资源包余额
      tags:
      - ImageFlix-资源包
  /users/{uuid}:
    get:
      description: 通过用户UUID获取用户的信息
      parameters:
      - description: 用户UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
            - properties:
                data:
                  $ref: '#/definitions/api_user.RespUserInfo'
              type: object
        "500":
          description: Internal Server Error
      security:
      - APIAuth: []
      summary: 获取用户的信息
      tags:
      - 用户
  /users/me:
    get:
      description: 获取当前登录用户的信息
      produces:
      - application/json
      responses:
        "200":
          description: code不为0时表示有错误
          schema:
            allOf:
            - $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
            - properties:
                data:
                  $ref: '#/definitions/api_user.RespUserInfo'
              type: object
        "500":
          description: Internal Server Error
      security:
      - APIAuth: []
      summary: 获取当前登录用户的信息
      tags:
      - 用户
  /users/me/password/update:
    post:
      consumes:
      - application/json
      description: 修改当前登录用户的登录密码
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api_user.ReqUpdateUserPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
      security:
      - APIAuth: []
      summary: 修改用户密码
      tags:
      - 用户
  /users/me/profile:
    get:
      description: 当前登录用户的个人资料
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
      security:
      - APIAuth: []
      summary: 用户个人资料
      tags:
      - 用户
  /users/me/profile/update:
    post:
      consumes:
      - application/json
      description: 更新当前登录用户的个人资料
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api_user.ReqUpdateUserProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
      security:
      - APIAuth: []
      summary: 更新用户个人资料
      tags:
      - 用户
  /users/me/update:
    post:
      consumes:
      - application/json
      description: 更新当前登录用户的基本信息
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api_user.ReqUpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/goal-app_pkg_render.RespJsonData'
      security:
      - APIAuth: []
      summary: 更新用户基本信息
      tags:
      - 用户
securityDefinitions:
  APIAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
