basePath: /api/v1
host: localhost
info:
  contact: {}
  title: 前端应用接口文档
  version: "1.0"
paths:
  /account/login:
    post:
      consumes:
      - application/json
      description: 前端应用的用户登录接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: 用户登录
      tags:
      - 登录
swagger: "2.0"
